services:
    eschmar_doctrine_routing.routing_loader:
        class: "Eschmar\DoctrineRoutingBundle\Service\DoctrineRoutingLoader"
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: routing.loader }

    eschmar_doctrine_routing.helper:
        arguments: [ %kernel.environment% ]
        class: "Eschmar\DoctrineRoutingBundle\Service\DoctrineRoutingHelper"